# 可恢复错误和 panic!

大多数错误并不需要完全停止整个程序。例如，如果打开一个不存在的文件，你可能会想创建这个文件而不是停止程序。

回想第二章中，`Result`枚举的两个成员，`Ok`和`Err`：

```rust
enum Result<T, E> {
    Ok(T),
    Err(E),
}
```

`T`和`E`都是泛型参数，我们将在第十章讲解。`T`代表成功时的返回类型，`E`代表失败时的返回类型。

举例：

```rust
use std::fs::File;

fn main() {
    let f = File::open("hello.txt");

    let f = match f {
        Ok(file) => file,
        Err(error) => panic!("Problem opening the file: {:?}", error),
    };
}
```

注意与`Option`枚举一样，`Result`枚举和它的成员也被 prelude 提前导入作用域了，因此我们不需要指定`Result::`在`Ok`和`Err`这两个成员前。

...

## 匹配不同的错误

```rust
use std::fs::File;
use std::io::ErrorKind;

fn main() {
    let f = File::open("hello.txt");

    let f = match f {
        Ok(file) => file,
        Err(error) => match error.kind() {
            ErrorKind::NotFound => match File::create("hello.txt") {
                Ok(fc) => fc,
                Err(e) => panic!("Problem creating the file: {:?}", e),
            },
            other_error => {
                panic!("Problem opening the file: {:?}", other_error)
            }
        },
    };
}
```

...

`match`表达式非常的有用但是还是很原始。在第十三章中我们将学到闭包；`Result<T, E>`类型有很多接受闭包的方法，它们都是有`match`表达式实现的。使用那些方法可以让你的代码更加简洁。一个有经验的 Rustacean 可能会这么写：

```rust
use std::fs::File;
use std::io::ErrorKind;

fn main() {
    let f = File::open("hello.txt").unwrap_or_else(|error| {
        if error.kind() == ErrorKind::NotFound {
            File::create("hello.txt").unwrap_or_else(|error| {
                panic!("Problem creating the file: {:?}", error);
            })
        } else {
            panic!("Problem opening the file: {:?}", error);
        }
    });
}
```

尽管上述代码的功效和之前是一样的，它没有包含任何`match`表达式并且更加便于阅读。完成第十三章后再回来看这个例子，还有`unwrap_or_else`标准库提供的方法。在处理错误时，有很多这类型的方法可以消除巨量的嵌套`match`表达式。

## 失败时 Panic 的简写：`unwarp`和`expect`

`Result<T, E>`类型还有很多辅助的方法来处理不同的情况。其中`unwrap`是一个类似于`match`表达式的简写。如果`Result`值是`Ok`，那么`unwarp`返回`Ok`内的值，反之调用`panic!`宏：

```rust
use std::fs::File;

fn main() {
    let f = File::open("hello.txt").unwrap();
}
```

另一个与`unwarp`类似的方法`expect`，让我们选择`panic!`的错误信息：

```rust
use std::fs::File;

fn main() {
    let f = File::open("hello.txt").expect("Failed to open hello.txt");
}
```

...

## 传播错误

编写函数式，你也可以返回错误给调用者，而不是在函数中处理错误。...

举例：

```rust
use std::fs::File;
use std::io;
use std::io::Read;

fn read_username_from_file() -> Result<String, io::Error> {
    let f = File::open("hello.txt");

    let mut f = match f {
        Ok(file) => file,
        Err(e) => return Err(e),
    };

    let mut s = String::new();

    match f.read_to_string(&mut s) {
        Ok(_) => Ok(s),
        Err(e) => Err(e),
    }
}
```

...

## 传播错误的简写：`?` 运算符

```rust
use std::fs::File;
use std::io;
use std::io::Read;

fn read_username_from_file() -> Result<String, io::Error> {
    let mut f = File::open("hello.txt")?;
    let mut s = String::new();
    f.read_to_string(&mut s)?;
    Ok(s)
}
```

`?`运算符放在一个`Result`值之后这么定义与`match`表达式功能一致。如果`Result`的值为`Ok`，那么将会返回`Ok`内的值，反之`Err`将会被返回，这样错误就被传播给了调用者。

使用`?`运算符与之前的`match`表达式有一个不同的地方在于：有`?`运算符的错误值被传递给了`from`函数，这是定义在标准库的`From`特性中，用于将转化错误成另一种类型。当`?`操作符调用了`from`函数，接收到的错误类型将会被转换成当前函数返回类型中指定的错误类型。

...

`?`运算符消除了大量样板代码使得函数的实现变得更简单。我们甚至可以在`?`后直接使用链式方法来进一步缩短代码：

```rust
use std::fs::File;
use std::io;
use std::io::Read;

fn read_username_from_file() -> Result<String, io::Error> {
    let mut s = String::new();

    File::open("hello.txt")?.read_to_string(&mut s)?;

    Ok(s)
}
```

还有一种更加简短的方式：

```rust
use std::fs;
use std::io;

fn read_username_from_file() -> Result<String, io::Error> {
    fs::read_to_string("hello.txt")
}
```

Rust 封装了读取文件并转为字符串这个常见的操作。

## `?`运算符可被用于返回值是`Result`的函数

`?`运算符可以作为返回类型为`Result`的函数的返回，因为它被定义为与`match`表达式一样的工作方式。`match`的`return Err(e)`部分要求返回值类型是`Result`，所以函数的返回值必须是一个`Result`才能与`return`匹配。

我们看一下如果在`main`函数使用`?`运算符会怎么样，回想一下`main`的返回类型是`()`：

```rust
use std::fs::File;

fn main() {
    let f = File::open("hello.txt")?;
}
```

报错如下：

```null
$ cargo run
   Compiling error-handling v0.1.0 (file:///projects/error-handling)
error[E0277]: the `?` operator can only be used in a function that returns `Result` or `Option` (or another type that implements `Try`)
 --> src/main.rs:4:13
  |
3 | / fn main() {
4 | |     let f = File::open("hello.txt")?;
  | |             ^^^^^^^^^^^^^^^^^^^^^^^^ cannot use the `?` operator in a function that returns `()`
5 | | }
  | |_- this function should return `Result` or `Option` to accept `?`
  |
  = help: the trait `Try` is not implemented for `()`
  = note: required by `from_error`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0277`.
error: could not compile `error-handling`

To learn more, run the command again with --verbose.
```

这个错误指出我们只允许在一个返回值是`Result`或`Option`或实现是`std::ops::Try`的函数使用`?`运算符。当你的返回值不是上述任意一个类型时，你任然希望使用`?`返回`Result<T, E>`时，你又两种解决方案。其一是把函数的返回类型改为`Result<T, E>`。其二是使用`match`或`Result<T, E>`的其中一个方法来处理自身。

`main`函数是特别的，它有对返回值类型的限制。一个有效的返回值是`()`，另一个是`Result<T, E>`，如下：

```rust
use std::error::Error;
use std::fs::File;

fn main() -> Result<(), Box<dyn Error>> {
    let f = File::open("hello.txt")?;

    Ok(())
}
```

`Box<dyn Error>`类型称为特性对象 trait object，我们将在第十七章讲到。现在只需要理解为“任意一种错误”就行了。这样的情况下使用`?`在`main`函数是被允许的。
