# 重构：模块化和错误处理

为了改进我们的程序，我们将解决关于项目结构和错误处理的四个问题。

第一个问题：我们的`main`函数有两个任务：解析参数和读取文件。...我们需要把功能分开，这样每个函数只做一件事。

第二个问题：`query`和`filename`是程序的配置变量，`contents`是逻辑变量。随之`main`增长我们需要把更多的变量引入作用域；而越多的变量在作用域中，我们越难追踪每个变量的目的。最好能配置变量组织进一个结构，这样能使他们的目的明确。

第三个问题：当读取文件失败时，我们使用`expect`来打印错误，但是错误只会是"Something went wrong reading the file"。我们需要更详细的错误信息。

第四个问题：如果用户没有指定足够的参数来运行程序，他们会从 Rust 得到`index out of bounds`错误，这并不能明确地解释问题。我们需要将所有的错误处理都放在一个地方，这样维护者在需要修改错误处理逻辑时只需要考虑这一处的代码。集中错误处理，也有助于确保我们打印的错误信息对我们和用户都有意义。

## 二进制项目的关注分离

`main`函数复杂多个任务的组织问题在很多二进制项目中比较常见。所以 Rust 社区开发出一类在`main`函数开始变庞大时进行二进制程序的关注分离的指导性过程：

- 讲程序拆分成*main.rs*和*lib.rs*，将程序的逻辑放入*lib.rs*。
- 只要命令行解析逻辑解析够小，可以保留在*main.rs*中
- 当命令行解析开始变得复杂时，也提取它到*lib.rs*中

这样`main`函数中的责任应该被限定为：

- 使用参数值调用命令行解析逻辑
- 市值任何其他的配置
- 调用*lib.rs*中的`run`函数
- 如果`run`返回错误，则处理这个错误

这个模式是为了分离关注：*main.rs*处理程序运行，*lib.rs*处理所有的任务逻辑。

### 提取参数解析器

我们将提取解析的功能至一个函数，方便`main`调用：

```rust
fn main() {
    let args: Vec<String> = env::args().collect();

    let (query, filename) = parse_config(&args);

    // --snip--
}

fn parse_config(args: &[String]) -> (&str, &str) {
    let query = &args[1];
    let filename = &args[2];

    (query, filename)
}
```

...

### 组合配置值

我们还可以做一个小的改进来改善`parse_config`函数。现阶段我们返回的是一个元组，但是我们使用的时候又打开了这个元组。这是可能一个我们使用的数据结构不当的信号。

我们可以构造一个结构体，并命名更有意义的字段：

```rust
fn main() {
    let args: Vec<String> = env::args().collect();

    let config = parse_config(&args);

    println!("Searching for {}", config.query);
    println!("In file {}", config.filename);

    let contents = fs::read_to_string(config.filename)
        .expect("Something went wrong reading the file");

    // --snip--
}

struct Config {
    query: String,
    filename: String,
}

fn parse_config(args: &[String]) -> Config {
    let query = args[1].clone();
    let filename = args[2].clone();

    Config { query, filename }
}
```

或者结构体使用引用值：

```rust
fn main() {
    let args: Vec<String> = env::args().collect();

    let config = parse_config(&args);

    println!("Searching for {}", config.query);
    println!("In file {}", config.filename);

    let contents = fs::read_to_string(config.filename)
        .expect("Something went wrong reading the file");

    println!("With text:\n{}", contents)
}

struct Config<'a> {
    query: &'a str,
    filename: &'a str,
}

fn parse_config<'a>(args: &'a Vec<String>) -> Config {
    let query = &args[1];
    let filename = &args[2];

    Config { query, filename }
}
```

...

### 为配置创建构造器

目前为止，我们提取了解析器的逻辑，并用`Config`结构体存放配置。那么我们给`Config`加一个关联函数：

```rust
fn main() {
    let args: Vec<String> = env::args().collect();

    let config = Config::new(&args);

    // --snip--
}

// --snip--

impl Config {
    fn new(args: &[String]) -> Config {
        let query = args[1].clone();
        let filename = args[2].clone();

        Config { query, filename }
    }
}
```

`Config<'a>`版本：

```rust
impl<'a> Config<'a> {
    fn new(args: &'a Vec<String>) -> Config {
        let query = &args[1];
        let filename = &args[2];

        Config { query, filename }
    }
}
```

...

## 改进错误处理

### 改进错误信息

我们可以改进`Config::new`方法：

```rust
    // --snip--
    fn new(args: &[String]) -> Config {
        if args.len() < 3 {
            panic!("not enough arguments");
        }
        // --snip--
```

...

### 返回`Result`而不是调用`panic!`

更进一步，我们可以返回`Result`值：

```rust
impl Config {
    fn new(args: &[String]) -> Result<Config, &str> {
        if args.len() < 3 {
            return Err("not enough arguments");
        }

        let query = args[1].clone();
        let filename = args[2].clone();

        Ok(Config { query, filename })
    }
}
```

...

### 调用`Config::new`以及错误处理

接着我们需要更新`main`的错误处理，并打印一个用户用好的信息：

```rust
use std::process;

fn main() {
    let args: Vec<String> = env::args().collect();

    let config = Config::new(&args).unwrap_or_else(|err| {
        println!("Problem parsing arguments: {}", err);
        process::exit(1);
    });

    // --snip--
```

上述代码中有一个之前没有被提及的由标准库提供的`unwrap_or_else`方法。它可以让我们定义一些自定义的非`panic!`错误处理。当`Result`是`Ok`时，这个方法的行为类似于`unwrap`返回`Ok`内部值；当`Err`时，改方法会调用一个闭包（_closure_），即一个定义作为参数传递给`unwrap_or_else`的匿名函数。闭包会在第十三章做讲解。现在只需要理解`unwrap_or_else`会将`Err`的内部值传递给闭包中位于两条竖线间的参数`err`。闭包中的代码在运行时可以使用这个`err`值。

运行结果很用户友好：

```null
$ cargo run
   Compiling minigrep v0.1.0 (file:///projects/minigrep)
    Finished dev [unoptimized + debuginfo] target(s) in 0.48s
     Running `target/debug/minigrep`
Problem parsing arguments: not enough arguments
```

## 从`main`中提取逻辑

现在我们完成了参数解析的重构，让我们开始程序的逻辑部分：

```rust
fn main() {
    // --snip--

    println!("Searching for {}", config.query);
    println!("In file {}", config.filename);

    run(config);
}

fn run(config: Config) {
    let contents = fs::read_to_string(config.filename)
        .expect("Something went wrong reading the file");

    println!("With text:\n{}", contents);
}

// --snip--
```

...

### `run`函数返回错误

不再通过`expect`允许程序 panic，`run`现在返回一个`Result`：

```rust
use std::error::Error;

// --snip--

fn run(config: Config) -> Result<(), Box<dyn Error>> {
    let contents = fs::read_to_string(config.filename)?;

    println!("With text:\n{}", contents);

    Ok(())
}
```

这里有三个重要的改变。第一，我们把返回类型改为了`Result<(), Box<dyn Error>>`。这个函数之前返回单元类型`()`，现在我们把它放入`Ok`里。而对于错误类型，我们使用了*特性对象*`Box<dyn Error>`（同时我们把`std::error::Error`引入作用域）。特性对象会在第十七章做讲解。现在只需要理解`Box<dyn Error>`意味着函数将会返回实现了`Error`特性的类型，并不再需要指定将会返回的类型。这提供了在不同错误场景下可能有不同类型的错误返回值的灵活性。

第二，我们用第九章讲到的`?`运算符代替了`expect`。与其对一个错误`panic!`，不如用`?`返回错误值再交给函数调用者来处理。

第三，函数成功时的返回`Ok`的值为`()`。`Ok(())`看起来有点奇怪，不过这样使用`()`是惯用的做法，表示调用`run`函数只是为了它的副作用；函数并没有返回一个我们需要的值。

现在可以编译，但是会有一个警告：

```null
$ cargo run the poem.txt
   Compiling minigrep v0.1.0 (file:///projects/minigrep)
warning: unused `std::result::Result` that must be used
  --> src/main.rs:19:5
   |
19 |     run(config);
   |     ^^^^^^^^^^^^
   |
   = note: `#[warn(unused_must_use)]` on by default
   = note: this `Result` may be an `Err` variant, which should be handled

warning: 1 warning emitted

    Finished dev [unoptimized + debuginfo] target(s) in 0.71s
     Running `target/debug/minigrep the poem.txt`
Searching for the
In file poem.txt
With text:
I’m nobody! Who are you?
Are you nobody, too?
Then there’s a pair of us - don’t tell!
They’d banish us, you know.

How dreary to be somebody!
How public, like a frog
To tell your name the livelong day
To an admiring bog!
```

Rust 告诉我们代码中忽略了`Result`值，这里有可能是个错误但是我们并没有检查。因此编译器提醒我们这里应该需要有错误处理。

### 在`main`调用`run`后的错误处理

`main`函数中加上错误处理：

```rust
fn main() {
    // --snip--

    println!("Searching for {}", config.query);
    println!("In file {}", config.filename);

    if let Err(e) = run(config) {
        println!("Application error: {}", e);

        process::exit(1);
    }
}
```

`if let`简化`match`模式。不同于`unwrap_or_else`，并在出错时调用`process::exit(1)`。`run`不像`Config::new`返回的`Config`实例需要`unwrap`的值，因为`run`返回`()`，我们只关心检测错误。

## 分离代码至库箱

现在我们要拆分*src/main.rs*并将一些代码放入*src/lib.rs*，这样就能进行单元测试，并且`main`函数更加清晰。

文件*src/lib.rs*：

```rust
use std::error::Error;
use std::fs;

pub struct Config<'a> {
    pub query: &'a str,
    pub filename: &'a str,
}

impl<'a> Config<'a> {
    pub fn new(args: &'a Vec<String>) -> Result<Config, &str> {
        if args.len() < 3 {
            return Err("not enough arguments");
        }

        let (query, filename) = (&args[1], &args[2]);

        Ok(Config { query, filename })
    }
}

pub fn run(config: Config) -> Result<(), Box<dyn Error>> {
    let contents = fs::read_to_string(config.filename)?;

    println!("With text:\n{}", contents);

    Ok(())
}
```

都加上了`pub`关键字。现在我们有了一个拥有可以测试公有 API 的库箱了。

接下来文件*src/main.rs*：

```rust
use std::env;
use std::process;

use minigrep::Config;

fn main() {
    let args: Vec<String> = env::args().collect();

    let config = Config::new(&args).unwrap_or_else(|err| {
        println!("Problem parsing arguments: {}", err);
        process::exit(1);
    });

    println!("Searching for {}", config.query);
    println!("In file {}", config.filename);

    if let Err(e) = minigrep::run(config) {
        println!("Application error: {}", e);

        process::exit(1);
    }
}
```

我们用了`use minigrep::Config`把`Config`类型引入作用域，并使用箱名称作为`run`函数的前缀。

...
