# 如何写测试

Rust 中的测试函数用于验证非测试代码是否按期望的方式运作的。测试函数体通常执行以下三种操作：

1. 设置任何需要的数据或状态
1. 运行需要被测试的代码
1. 断言我们所期望的结果

## 测试函数剖析

最简单的例子，Rust 有一个`test`属性的注解函数。属性是 Rust 代码片段的元数据；第五章用到的`derive`属性就是一个例子。改变一个函数成测试函数，需要在`fn`的上一行加上`#[test]`。当你使用`cargo test`命令执行测试时，Rust 会构建一个测试执行程序用来调用标记了`test`属性的函数，并报告每一个测试是否通过。

创建一个新的库项目`adder`：

```null
$ cargo new adder --lib
     Created library `adder` project
$ cd adder
```

*src/lib.rs*文件如下：

```rust
#[cfg(test)]
mod tests {
    #[test]
    fn it_works() {
        assert_eq!(2 + 2, 4);
    }
}

```

暂且先不看头两行，我们注意函数是如何工作的。注意在`fn`前的`#[test]`注解：这个属性表示这是一个测试函数，所以测试执行器将会将其作为测试处理。

使用`cargo test`：

```null
$ cargo test
   Compiling adder v0.1.0 (file:///projects/adder)
    Finished test [unoptimized + debuginfo] target(s) in 0.57s
     Running target/debug/deps/adder-92948b65e88960b4

running 1 test
test tests::it_works ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

   Doc-tests adder

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out
```

在`running 1 test`的下一行，显示了测试函数的名称`it_works`，以及测试的结果`ok`。接下来是所有测试的总结。

...

接下来的一部分开始于`Doc-tests adder`，是所有的文档测试结果。我们暂时还没有任何文档测试，但是 Rust 可以编译任何在 API 文档中出现的案例代码。...

...

让我们再加上一个测试，这一次我们要让测试失败！当测试函数中出现 panic 时测试就失败了。每一个测试都在一个新的线程中运行，当主线程发现测试线程一场了，就将对应测试标记为失败：

```rust
#[cfg(test)]
mod tests {
    #[test]
    fn exploration() {
        assert_eq!(2 + 2, 4);
    }

    #[test]
    fn another() {
        panic!("Make this test fail");
    }
}
```

结果：

```null
$ cargo test
   Compiling adder v0.1.0 (file:///projects/adder)
    Finished test [unoptimized + debuginfo] target(s) in 0.72s
     Running target/debug/deps/adder-92948b65e88960b4

running 2 tests
test tests::another ... FAILED
test tests::exploration ... ok

failures:

---- tests::another stdout ----
thread 'main' panicked at 'Make this test fail', src/lib.rs:10:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    tests::another

test result: FAILED. 1 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out

error: test failed, to rerun pass '--lib'
```

...

## 通过`assert!`宏检查结果

标准库提供的`assert!`宏用于断言测试中的条件是否成立，其求值为布尔型。`true`时通过测试，`false`时将调用`panic!`宏。

第五章中我们用`Rectangle`结构体以及其`can_hold`方法，这里我们拿来测试：

```rust
#[derive(Debug)]
struct Rectangle {
    width: u32,
    height: u32,
}

impl Rectangle {
    fn can_hold(&self, other: &Rectangle) -> bool {
        self.width > other.width && self.height > other.height
    }
}
```

`can_hold`方法返回的是布尔型，这样可以非常方便的运用在`assert!`宏里。接下来创建两个实例，再断言：

```rust
#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn larger_can_hold_smaller() {
        let larger = Rectangle {
            width: 8,
            height: 7,
        };
        let smaller = Rectangle {
            width: 5,
            height: 1,
        };

        assert!(larger.can_hold(&smaller));
    }
}
```

注意我们用到了`use super::*`来引用父级的`Rectangle`和其`impl`。结果：

```null
$ cargo test
   Compiling rectangle v0.1.0 (file:///projects/rectangle)
    Finished test [unoptimized + debuginfo] target(s) in 0.66s
     Running target/debug/deps/rectangle-6584c4561e48942e

running 1 test
test tests::larger_can_hold_smaller ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

   Doc-tests rectangle

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out
```

再加一个测试：

```rust
#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn larger_can_hold_smaller() {
        // --snip--
    }

    #[test]
    fn smaller_cannot_hold_larger() {
        let larger = Rectangle {
            width: 8,
            height: 7,
        };
        let smaller = Rectangle {
            width: 5,
            height: 1,
        };

        assert!(!smaller.can_hold(&larger));
    }
}
```

结果：

```null
$ cargo test
   Compiling rectangle v0.1.0 (file:///projects/rectangle)
    Finished test [unoptimized + debuginfo] target(s) in 0.66s
     Running target/debug/deps/rectangle-6584c4561e48942e

running 2 tests
test tests::larger_can_hold_smaller ... ok
test tests::smaller_cannot_hold_larger ... ok

test result: ok. 2 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

   Doc-tests rectangle

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out
```

...

## 通过`assert_eq!`和`assert_ne!`宏测试等式

`assert_eq!`用于测试两值相等，`assert_ne!`用于测试两值不等。

...

```rust
pub fn add_two(a: i32) -> i32 {
    a + 2
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn it_adds_two() {
        assert_eq!(4, add_two(2));
    }
}
```

...

## 添加自定义失败信息

我们可以像`assert!`，`assert_eq!`和`assert_ne!`宏传递一个可选的失败信息参数，以便在测试失败时一起打印出来：

```rust
    #[test]
    fn greeting_contains_name() {
        let result = greeting("Carol");
        assert!(
            result.contains("Carol"),
            "Greeting did not contain name, value was `{}`",
            result
        );
    }
```

...

## 通过`should_panic`检查 Panics

除了检查我们的代码的返回值是否是我们预期的，检查错误处理是否如同预期也是同样重要的。例如，第九章的`Guess`类型，为了确保`Guess`实例只能包含 1 到 100 的值，我们可以写一个测试。

我们用到另一个属性，`should_panic`，用于我们的测试函数。只要在函数内的代码 panic，这个属性就让测试通过；反之，不 panic 不通过：

```rust
pub struct Guess {
    value: i32,
}

impl Guess {
    pub fn new(value: i32) -> Guess {
        if value < 1 || value > 100 {
            panic!("Guess value must be between 1 and 100, got {}.", value);
        }

        Guess { value }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    #[should_panic]
    fn greater_than_100() {
        Guess::new(200);
    }
}
```

我们在`#[test]`和`fn`中间一行加上`#[should_panic]`属性，测试通过了：

```null
$ cargo test
   Compiling guessing_game v0.1.0 (file:///projects/guessing_game)
    Finished test [unoptimized + debuginfo] target(s) in 0.58s
     Running target/debug/deps/guessing_game-57d70c3acb738f4d

running 1 test
test tests::greater_than_100 ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

   Doc-tests guessing_game

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out
```

...

使用`should_panic`测试可能会不确切，因为它们只是告诉我们代码没有产生 panic。甚至在一些不是我们期望的原因而导致 panic 时也会通过。为了让`should_panic`测试结果更加精确，我们可以加一个可选的`expected`参数进`should_panic`属性中：

```rust
// --snip--
impl Guess {
    pub fn new(value: i32) -> Guess {
        if value < 1 {
            panic!(
                "Guess value must be greater than or equal to 1, got {}.",
                value
            );
        } else if value > 100 {
            panic!(
                "Guess value must be less than or equal to 100, got {}.",
                value
            );
        }

        Guess { value }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    #[should_panic(expected = "Guess value must be less than or equal to 100")]
    fn greater_than_100() {
        Guess::new(200);
    }
}
```

...

## 测试中使用`Result<T, E>`

我们也可以使用`Result<T, E>`来编写测试：

```rust
#[cfg(test)]
mod tests {
    #[test]
    fn it_works() -> Result<(), String> {
        if 2 + 2 == 4 {
            Ok(())
        } else {
            Err(String::from("two plus two does not equal four"))
        }
    }
}
```

...
